name: Minecraft Bedrock AFK Bot

on:
  push:
    branches: [ "main" ]
  schedule:
    # يعمل تلقائياً كل 15 دقيقة لإنعاش السيرفر وضمان عدم إغلاقه
    - cron: '*/15 * * * *'

jobs:
  run-bedrock-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install NPM Dependencies
      run: npm install

    - name: Execute Bedrock Bot
      run: node bot.js
      # نضع حداً أقصى لتشغيل الأكشن (25 دقيقة) حتى لا يستهلك ساعات GitHub المجانية بسرعة
      timeout-minutes: 25
